### ISSUE TITLE
win10 运行点击按钮没有反应

### ISSUE THREAD

**Issue by diybl** [xtuzy/Veldrid.Samples#5]
界面的颜色 也跟演示视频上的不太一样 是不是 缺少资源文件？

我运行的是maui的 samples

**Comment by xtuzy** [comment]
首先你是否是按照https://github.com/xtuzy/Veldrid.Samples/wiki/How-to-use 使用了我的github上的包，使用官方veldrid在nuget上的包是没有用的。

如果你使用的包对了，那可能是maui的问题，像例子中的画三角形，它都不需要图片资源，如果你点击对应的按钮还不显示，那我也不知道为啥，当然在这之前你得设置断点确认clicked事件是被调用了。

**Comment by diybl** [comment]
> 首先你是否是按照https://github.com/xtuzy/Veldrid.Samples/wiki/How-to-use 使用了我的github上的包，使用官方veldrid在nuget上的包是没有用的。
> 
> 如果你使用的包对了，那可能是maui的问题，像例子中的画三角形，它都不需要图片资源，如果你点击对应的按钮还不显示，那我也不知道为啥，当然在这之前你得设置断点确认clicked事件是被调用了。

我是在win10下运行的
我看 Veldrid.Maui.Controls 下 
windows platform里的 VeldridPlatformView 这个class是空的 没有定义 是这个原因吗？？

**Comment by diybl** [comment]
不折腾了 maui 搞游戏太坑了。。
我换stride3d了 好像是微软的
所以微软就没计划让maui来支持游戏。。

**Comment by xtuzy** [comment]
stride3d它不是微软的吧，反正纯c#的游戏引擎好像就它和monogame完善点。为啥不直接上unity呢，资源和学习资料更多

**Comment by diybl** [comment]
> stride3d它不是微软的吧，反正纯c#的游戏引擎好像就它和monogame完善点。为啥不直接上unity呢，资源和学习资料更多

加入.NET foundation了 他。
unity不好用 对程序员来说 而且他不开源。
